#!/usr/bin/python3
import json
import os

# Read schacon.repos.json and load data
with open('./data/schacon.repos.json', 'r') as file:
    data = json.load(file)

output_file = 'chacon.csv' # create variable to call chacon.csv
with open(output_file, 'a') as file: # read the file
    # loop through first five data entries and collect the specified info for each entry
    for d in data[:5]:
        name = d['name']
        html_url = d['html_url']
        updated_at = d['updated_at']
        visibility = d['visibility']
        # create a line which assembles the specified info for the entry
        print_line = f"{name},{html_url},{updated_at},{visibility}\n"
        # print this line into the file
        file.write(print_line)
